name: Deploy to EC2

on: 
    push:
        branches: 
            - main

jobs: 
    deploy:
        runs-on: ubuntu-latest
        steps: 
            - name: SSH로 EC2로 접속하기
                uses: appleboy/ssh-action@v1.0.3
                with: 
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.KEY }}
                    script: |
                        cd /home/2024devEc2GitAction
                        git config --global --add safe.directory /home/2024devEc2GitAction
                        sudo git pull origin main
                        sudo ./gradlew bootWar
                        sudo fuser -k -n tcp 8080
                        sudo nohup java -jar /build/libs/*SNAPSHOT.war > /dev/null 2>&1 &
